const CREATE_COURSE = 'CREATE_COURSE';
const LOAD_COURSES_SUCCESS = 'loadCoursesSuccess';
const LOAD_AUTHOR_SUCCESS = 'loadAuthorSuccess';
const UPDATE_COURSES_SUCCESS = 'updateCourseSuccess';
const CREATE_COURSES_SUCCESS = 'createCourseSuccess';

export {
  CREATE_COURSE,
  LOAD_COURSES_SUCCESS,
  LOAD_AUTHOR_SUCCESS,
  UPDATE_COURSES_SUCCESS,
  CREATE_COURSES_SUCCESS
}
