const CREATE_COURSE = 'CREATE_COURSE';
const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
const LOAD_AUTHOR_SUCCESS = 'LOAD_AUTHOR_SUCCESS';
const UPDATE_COURSES_SUCCESS = 'UPDATE_COURSES_SUCCESS';
const CREATE_COURSES_SUCCESS = 'CREATE_COURSES_SUCCESS';
const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';

export {
  CREATE_COURSE,
  LOAD_COURSES_SUCCESS,
  LOAD_AUTHOR_SUCCESS,
  UPDATE_COURSES_SUCCESS,
  CREATE_COURSES_SUCCESS,
  BEGIN_AJAX_CALL
}
