const CREATE_COURSE = 'CREATE_COURSE';
const LOAD_COURSES_SUCCESS = 'loadCoursesSuccess';
const LOAD_AUTHOR_SUCCESS = 'loadAuthorSuccess';

export {
  CREATE_COURSE,
  LOAD_COURSES_SUCCESS,
  LOAD_AUTHOR_SUCCESS
}
